// Supabase Edge Function: send-sms-hook
// Supabase "Send SMS Hook" — invoked by Auth when signInWithOtp({ phone }) needs
// to deliver a code. Supabase generates the OTP and POSTs {user, sms} here; we
// relay it as an SMS via 1sms.az (instead of the built-in provider). Secrets
// (ONESMS_API_KEY, SEND_SMS_HOOK_SECRET) live in Supabase secrets — never here.
// Deploy: `supabase functions deploy send-sms-hook --no-verify-jwt`
// (the hook authenticates via the standard-webhooks signature, not a user JWT).

import { Webhook } from "https://esm.sh/standardwebhooks@1.0.0";

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

Deno.serve(async (req: Request) => {
  // Server-to-server POST only — no CORS/OPTIONS needed.
  if (req.method !== "POST") {
    return json(405, { error: { http_code: 405, message: "Method not allowed" } });
  }

  // Raw body text is required for signature verification (parse only after).
  const payload = await req.text();
  const headers = Object.fromEntries(req.headers);

  const hookSecret = Deno.env.get("SEND_SMS_HOOK_SECRET");
  if (!hookSecret) {
    console.error("missing SEND_SMS_HOOK_SECRET");
    return json(500, { error: { http_code: 500, message: "hook not configured" } });
  }

  // Verify the request is genuinely from Supabase (standard-webhooks signature).
  const base64Secret = hookSecret.replace("v1,whsec_", "");
  const wh = new Webhook(base64Secret);

  let user: { phone: string };
  let sms: { otp: string };
  try {
    const verified = wh.verify(payload, headers) as { user: { phone: string }; sms: { otp: string } };
    user = verified.user;
    sms = verified.sms;
  } catch (e) {
    console.error("webhook verify failed:", e);
    return json(401, { error: { http_code: 401, message: "invalid signature" } });
  }

  const phone = user?.phone; // E.164, e.g. +994506752777
  const otp = sms?.otp; // code generated by Supabase
  if (!phone || !otp) {
    return json(400, { error: { http_code: 400, message: "missing phone or otp" } });
  }

  const apiKey = Deno.env.get("ONESMS_API_KEY");
  if (!apiKey) {
    console.error("missing ONESMS_API_KEY");
    return json(500, { error: { http_code: 500, message: "sms provider not configured" } });
  }

  const messageText = `Tesdiq kodu: ${otp}. Kodu hech kese demeyin.`;

  try {
    const smsRes = await fetch("https://1sms.az/api/v1/sms/otp", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": apiKey,
      },
      body: JSON.stringify({
        to: phone,
        text: messageText,
        senderName: "Yuva",
      }),
    });
    const smsBody = await smsRes.text();
    if (!smsRes.ok) {
      console.error("1sms send failed:", smsRes.status, smsBody);
      return json(smsRes.status, { error: { http_code: smsRes.status, message: "sms send failed" } });
    }
    // 1sms can answer HTTP 200 with success=false (e.g. insufficient_balance).
    try {
      const parsed = JSON.parse(smsBody);
      if (parsed.success !== true) {
        console.error("1sms returned success=false:", smsBody);
        return json(502, { error: { http_code: 502, message: "sms not accepted" } });
      }
      console.log("1sms sent ok, balance:", parsed.balance);
    } catch {
      // Body isn't JSON but HTTP was ok → treat as sent, log for inspection.
      console.log("1sms sent (non-JSON ok):", smsBody);
    }
  } catch (e) {
    console.error("1sms fetch error:", e);
    return json(500, { error: { http_code: 500, message: "sms send error" } });
  }

  // Success — Supabase expects an empty JSON 200.
  return json(200, {});
});
